<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Styles\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MagicWok.Epos.Domain\MagicWok.Epos.Domain.csproj" />
    <ProjectReference Include="..\MagicWok.Epos.Hardware\MagicWok.Epos.Hardware.csproj" />
    <ProjectReference Include="..\MagicWok.Epos.Online\MagicWok.Epos.Online.csproj" />
    <ProjectReference Include="..\MagicWok.Epos.Data\MagicWok.Epos.Data.csproj" />
  </ItemGroup>
</Project>
